package com.sunwj.mybatis.bean;

import java.util.Date;

public class TfpayBaddebtOrders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.CHANNEL_ORDER_ID
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private String channelOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.AGENT_ORDER_NO
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private String agentOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.SERVNUMBER
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private String servnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.BADNUMBER
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private String badnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.CUSTID
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private String custid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.SMSMOBILENO
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private String smsmobileno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.OVERFEETYPE
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private Integer overfeetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.PAYFEE
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private Integer payfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.BRANCH
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private String branch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.STATE
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.BOSSID
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private String bossid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.APPLYOID
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private String applyoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.ORDERTIME
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private Date ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.PAYTIME
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private Date paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.TRANSTIME
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private Date transtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.PAYTYPE
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private String paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.AGENT_CODE
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private String agentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.SUB_CHANNEL
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private String subChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TF_PAYBADDEBT_ORDERS.CHANNEL
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    private String channel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.CHANNEL_ORDER_ID
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.CHANNEL_ORDER_ID
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public String getChannelOrderId() {
        return channelOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.CHANNEL_ORDER_ID
     *
     * @param channelOrderId the value for TF_PAYBADDEBT_ORDERS.CHANNEL_ORDER_ID
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setChannelOrderId(String channelOrderId) {
        this.channelOrderId = channelOrderId == null ? null : channelOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.AGENT_ORDER_NO
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.AGENT_ORDER_NO
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public String getAgentOrderNo() {
        return agentOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.AGENT_ORDER_NO
     *
     * @param agentOrderNo the value for TF_PAYBADDEBT_ORDERS.AGENT_ORDER_NO
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setAgentOrderNo(String agentOrderNo) {
        this.agentOrderNo = agentOrderNo == null ? null : agentOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.SERVNUMBER
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.SERVNUMBER
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public String getServnumber() {
        return servnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.SERVNUMBER
     *
     * @param servnumber the value for TF_PAYBADDEBT_ORDERS.SERVNUMBER
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setServnumber(String servnumber) {
        this.servnumber = servnumber == null ? null : servnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.BADNUMBER
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.BADNUMBER
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public String getBadnumber() {
        return badnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.BADNUMBER
     *
     * @param badnumber the value for TF_PAYBADDEBT_ORDERS.BADNUMBER
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setBadnumber(String badnumber) {
        this.badnumber = badnumber == null ? null : badnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.CUSTID
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.CUSTID
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public String getCustid() {
        return custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.CUSTID
     *
     * @param custid the value for TF_PAYBADDEBT_ORDERS.CUSTID
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setCustid(String custid) {
        this.custid = custid == null ? null : custid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.SMSMOBILENO
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.SMSMOBILENO
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public String getSmsmobileno() {
        return smsmobileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.SMSMOBILENO
     *
     * @param smsmobileno the value for TF_PAYBADDEBT_ORDERS.SMSMOBILENO
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setSmsmobileno(String smsmobileno) {
        this.smsmobileno = smsmobileno == null ? null : smsmobileno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.OVERFEETYPE
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.OVERFEETYPE
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public Integer getOverfeetype() {
        return overfeetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.OVERFEETYPE
     *
     * @param overfeetype the value for TF_PAYBADDEBT_ORDERS.OVERFEETYPE
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setOverfeetype(Integer overfeetype) {
        this.overfeetype = overfeetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.PAYFEE
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.PAYFEE
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public Integer getPayfee() {
        return payfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.PAYFEE
     *
     * @param payfee the value for TF_PAYBADDEBT_ORDERS.PAYFEE
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setPayfee(Integer payfee) {
        this.payfee = payfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.BRANCH
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.BRANCH
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.BRANCH
     *
     * @param branch the value for TF_PAYBADDEBT_ORDERS.BRANCH
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setBranch(String branch) {
        this.branch = branch == null ? null : branch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.STATE
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.STATE
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.STATE
     *
     * @param state the value for TF_PAYBADDEBT_ORDERS.STATE
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.BOSSID
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.BOSSID
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public String getBossid() {
        return bossid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.BOSSID
     *
     * @param bossid the value for TF_PAYBADDEBT_ORDERS.BOSSID
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setBossid(String bossid) {
        this.bossid = bossid == null ? null : bossid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.APPLYOID
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.APPLYOID
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public String getApplyoid() {
        return applyoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.APPLYOID
     *
     * @param applyoid the value for TF_PAYBADDEBT_ORDERS.APPLYOID
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setApplyoid(String applyoid) {
        this.applyoid = applyoid == null ? null : applyoid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.ORDERTIME
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.ORDERTIME
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.ORDERTIME
     *
     * @param ordertime the value for TF_PAYBADDEBT_ORDERS.ORDERTIME
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.PAYTIME
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.PAYTIME
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.PAYTIME
     *
     * @param paytime the value for TF_PAYBADDEBT_ORDERS.PAYTIME
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.TRANSTIME
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.TRANSTIME
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public Date getTranstime() {
        return transtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.TRANSTIME
     *
     * @param transtime the value for TF_PAYBADDEBT_ORDERS.TRANSTIME
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setTranstime(Date transtime) {
        this.transtime = transtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.PAYTYPE
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.PAYTYPE
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.PAYTYPE
     *
     * @param paytype the value for TF_PAYBADDEBT_ORDERS.PAYTYPE
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.AGENT_CODE
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.AGENT_CODE
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public String getAgentCode() {
        return agentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.AGENT_CODE
     *
     * @param agentCode the value for TF_PAYBADDEBT_ORDERS.AGENT_CODE
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode == null ? null : agentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.SUB_CHANNEL
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.SUB_CHANNEL
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public String getSubChannel() {
        return subChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.SUB_CHANNEL
     *
     * @param subChannel the value for TF_PAYBADDEBT_ORDERS.SUB_CHANNEL
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setSubChannel(String subChannel) {
        this.subChannel = subChannel == null ? null : subChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_PAYBADDEBT_ORDERS.CHANNEL
     *
     * @return the value of TF_PAYBADDEBT_ORDERS.CHANNEL
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_PAYBADDEBT_ORDERS.CHANNEL
     *
     * @param channel the value for TF_PAYBADDEBT_ORDERS.CHANNEL
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }
}