package com.sunwj.mybatis.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TfpayBaddebtOrdersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public TfpayBaddebtOrdersExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChannelOrderIdIsNull() {
            addCriterion("CHANNEL_ORDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andChannelOrderIdIsNotNull() {
            addCriterion("CHANNEL_ORDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andChannelOrderIdEqualTo(String value) {
            addCriterion("CHANNEL_ORDER_ID =", value, "channelOrderId");
            return (Criteria) this;
        }

        public Criteria andChannelOrderIdNotEqualTo(String value) {
            addCriterion("CHANNEL_ORDER_ID <>", value, "channelOrderId");
            return (Criteria) this;
        }

        public Criteria andChannelOrderIdGreaterThan(String value) {
            addCriterion("CHANNEL_ORDER_ID >", value, "channelOrderId");
            return (Criteria) this;
        }

        public Criteria andChannelOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL_ORDER_ID >=", value, "channelOrderId");
            return (Criteria) this;
        }

        public Criteria andChannelOrderIdLessThan(String value) {
            addCriterion("CHANNEL_ORDER_ID <", value, "channelOrderId");
            return (Criteria) this;
        }

        public Criteria andChannelOrderIdLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL_ORDER_ID <=", value, "channelOrderId");
            return (Criteria) this;
        }

        public Criteria andChannelOrderIdLike(String value) {
            addCriterion("CHANNEL_ORDER_ID like", value, "channelOrderId");
            return (Criteria) this;
        }

        public Criteria andChannelOrderIdNotLike(String value) {
            addCriterion("CHANNEL_ORDER_ID not like", value, "channelOrderId");
            return (Criteria) this;
        }

        public Criteria andChannelOrderIdIn(List<String> values) {
            addCriterion("CHANNEL_ORDER_ID in", values, "channelOrderId");
            return (Criteria) this;
        }

        public Criteria andChannelOrderIdNotIn(List<String> values) {
            addCriterion("CHANNEL_ORDER_ID not in", values, "channelOrderId");
            return (Criteria) this;
        }

        public Criteria andChannelOrderIdBetween(String value1, String value2) {
            addCriterion("CHANNEL_ORDER_ID between", value1, value2, "channelOrderId");
            return (Criteria) this;
        }

        public Criteria andChannelOrderIdNotBetween(String value1, String value2) {
            addCriterion("CHANNEL_ORDER_ID not between", value1, value2, "channelOrderId");
            return (Criteria) this;
        }

        public Criteria andAgentOrderNoIsNull() {
            addCriterion("AGENT_ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andAgentOrderNoIsNotNull() {
            addCriterion("AGENT_ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAgentOrderNoEqualTo(String value) {
            addCriterion("AGENT_ORDER_NO =", value, "agentOrderNo");
            return (Criteria) this;
        }

        public Criteria andAgentOrderNoNotEqualTo(String value) {
            addCriterion("AGENT_ORDER_NO <>", value, "agentOrderNo");
            return (Criteria) this;
        }

        public Criteria andAgentOrderNoGreaterThan(String value) {
            addCriterion("AGENT_ORDER_NO >", value, "agentOrderNo");
            return (Criteria) this;
        }

        public Criteria andAgentOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("AGENT_ORDER_NO >=", value, "agentOrderNo");
            return (Criteria) this;
        }

        public Criteria andAgentOrderNoLessThan(String value) {
            addCriterion("AGENT_ORDER_NO <", value, "agentOrderNo");
            return (Criteria) this;
        }

        public Criteria andAgentOrderNoLessThanOrEqualTo(String value) {
            addCriterion("AGENT_ORDER_NO <=", value, "agentOrderNo");
            return (Criteria) this;
        }

        public Criteria andAgentOrderNoLike(String value) {
            addCriterion("AGENT_ORDER_NO like", value, "agentOrderNo");
            return (Criteria) this;
        }

        public Criteria andAgentOrderNoNotLike(String value) {
            addCriterion("AGENT_ORDER_NO not like", value, "agentOrderNo");
            return (Criteria) this;
        }

        public Criteria andAgentOrderNoIn(List<String> values) {
            addCriterion("AGENT_ORDER_NO in", values, "agentOrderNo");
            return (Criteria) this;
        }

        public Criteria andAgentOrderNoNotIn(List<String> values) {
            addCriterion("AGENT_ORDER_NO not in", values, "agentOrderNo");
            return (Criteria) this;
        }

        public Criteria andAgentOrderNoBetween(String value1, String value2) {
            addCriterion("AGENT_ORDER_NO between", value1, value2, "agentOrderNo");
            return (Criteria) this;
        }

        public Criteria andAgentOrderNoNotBetween(String value1, String value2) {
            addCriterion("AGENT_ORDER_NO not between", value1, value2, "agentOrderNo");
            return (Criteria) this;
        }

        public Criteria andServnumberIsNull() {
            addCriterion("SERVNUMBER is null");
            return (Criteria) this;
        }

        public Criteria andServnumberIsNotNull() {
            addCriterion("SERVNUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andServnumberEqualTo(String value) {
            addCriterion("SERVNUMBER =", value, "servnumber");
            return (Criteria) this;
        }

        public Criteria andServnumberNotEqualTo(String value) {
            addCriterion("SERVNUMBER <>", value, "servnumber");
            return (Criteria) this;
        }

        public Criteria andServnumberGreaterThan(String value) {
            addCriterion("SERVNUMBER >", value, "servnumber");
            return (Criteria) this;
        }

        public Criteria andServnumberGreaterThanOrEqualTo(String value) {
            addCriterion("SERVNUMBER >=", value, "servnumber");
            return (Criteria) this;
        }

        public Criteria andServnumberLessThan(String value) {
            addCriterion("SERVNUMBER <", value, "servnumber");
            return (Criteria) this;
        }

        public Criteria andServnumberLessThanOrEqualTo(String value) {
            addCriterion("SERVNUMBER <=", value, "servnumber");
            return (Criteria) this;
        }

        public Criteria andServnumberLike(String value) {
            addCriterion("SERVNUMBER like", value, "servnumber");
            return (Criteria) this;
        }

        public Criteria andServnumberNotLike(String value) {
            addCriterion("SERVNUMBER not like", value, "servnumber");
            return (Criteria) this;
        }

        public Criteria andServnumberIn(List<String> values) {
            addCriterion("SERVNUMBER in", values, "servnumber");
            return (Criteria) this;
        }

        public Criteria andServnumberNotIn(List<String> values) {
            addCriterion("SERVNUMBER not in", values, "servnumber");
            return (Criteria) this;
        }

        public Criteria andServnumberBetween(String value1, String value2) {
            addCriterion("SERVNUMBER between", value1, value2, "servnumber");
            return (Criteria) this;
        }

        public Criteria andServnumberNotBetween(String value1, String value2) {
            addCriterion("SERVNUMBER not between", value1, value2, "servnumber");
            return (Criteria) this;
        }

        public Criteria andBadnumberIsNull() {
            addCriterion("BADNUMBER is null");
            return (Criteria) this;
        }

        public Criteria andBadnumberIsNotNull() {
            addCriterion("BADNUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andBadnumberEqualTo(String value) {
            addCriterion("BADNUMBER =", value, "badnumber");
            return (Criteria) this;
        }

        public Criteria andBadnumberNotEqualTo(String value) {
            addCriterion("BADNUMBER <>", value, "badnumber");
            return (Criteria) this;
        }

        public Criteria andBadnumberGreaterThan(String value) {
            addCriterion("BADNUMBER >", value, "badnumber");
            return (Criteria) this;
        }

        public Criteria andBadnumberGreaterThanOrEqualTo(String value) {
            addCriterion("BADNUMBER >=", value, "badnumber");
            return (Criteria) this;
        }

        public Criteria andBadnumberLessThan(String value) {
            addCriterion("BADNUMBER <", value, "badnumber");
            return (Criteria) this;
        }

        public Criteria andBadnumberLessThanOrEqualTo(String value) {
            addCriterion("BADNUMBER <=", value, "badnumber");
            return (Criteria) this;
        }

        public Criteria andBadnumberLike(String value) {
            addCriterion("BADNUMBER like", value, "badnumber");
            return (Criteria) this;
        }

        public Criteria andBadnumberNotLike(String value) {
            addCriterion("BADNUMBER not like", value, "badnumber");
            return (Criteria) this;
        }

        public Criteria andBadnumberIn(List<String> values) {
            addCriterion("BADNUMBER in", values, "badnumber");
            return (Criteria) this;
        }

        public Criteria andBadnumberNotIn(List<String> values) {
            addCriterion("BADNUMBER not in", values, "badnumber");
            return (Criteria) this;
        }

        public Criteria andBadnumberBetween(String value1, String value2) {
            addCriterion("BADNUMBER between", value1, value2, "badnumber");
            return (Criteria) this;
        }

        public Criteria andBadnumberNotBetween(String value1, String value2) {
            addCriterion("BADNUMBER not between", value1, value2, "badnumber");
            return (Criteria) this;
        }

        public Criteria andCustidIsNull() {
            addCriterion("CUSTID is null");
            return (Criteria) this;
        }

        public Criteria andCustidIsNotNull() {
            addCriterion("CUSTID is not null");
            return (Criteria) this;
        }

        public Criteria andCustidEqualTo(String value) {
            addCriterion("CUSTID =", value, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidNotEqualTo(String value) {
            addCriterion("CUSTID <>", value, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidGreaterThan(String value) {
            addCriterion("CUSTID >", value, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTID >=", value, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidLessThan(String value) {
            addCriterion("CUSTID <", value, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidLessThanOrEqualTo(String value) {
            addCriterion("CUSTID <=", value, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidLike(String value) {
            addCriterion("CUSTID like", value, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidNotLike(String value) {
            addCriterion("CUSTID not like", value, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidIn(List<String> values) {
            addCriterion("CUSTID in", values, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidNotIn(List<String> values) {
            addCriterion("CUSTID not in", values, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidBetween(String value1, String value2) {
            addCriterion("CUSTID between", value1, value2, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidNotBetween(String value1, String value2) {
            addCriterion("CUSTID not between", value1, value2, "custid");
            return (Criteria) this;
        }

        public Criteria andSmsmobilenoIsNull() {
            addCriterion("SMSMOBILENO is null");
            return (Criteria) this;
        }

        public Criteria andSmsmobilenoIsNotNull() {
            addCriterion("SMSMOBILENO is not null");
            return (Criteria) this;
        }

        public Criteria andSmsmobilenoEqualTo(String value) {
            addCriterion("SMSMOBILENO =", value, "smsmobileno");
            return (Criteria) this;
        }

        public Criteria andSmsmobilenoNotEqualTo(String value) {
            addCriterion("SMSMOBILENO <>", value, "smsmobileno");
            return (Criteria) this;
        }

        public Criteria andSmsmobilenoGreaterThan(String value) {
            addCriterion("SMSMOBILENO >", value, "smsmobileno");
            return (Criteria) this;
        }

        public Criteria andSmsmobilenoGreaterThanOrEqualTo(String value) {
            addCriterion("SMSMOBILENO >=", value, "smsmobileno");
            return (Criteria) this;
        }

        public Criteria andSmsmobilenoLessThan(String value) {
            addCriterion("SMSMOBILENO <", value, "smsmobileno");
            return (Criteria) this;
        }

        public Criteria andSmsmobilenoLessThanOrEqualTo(String value) {
            addCriterion("SMSMOBILENO <=", value, "smsmobileno");
            return (Criteria) this;
        }

        public Criteria andSmsmobilenoLike(String value) {
            addCriterion("SMSMOBILENO like", value, "smsmobileno");
            return (Criteria) this;
        }

        public Criteria andSmsmobilenoNotLike(String value) {
            addCriterion("SMSMOBILENO not like", value, "smsmobileno");
            return (Criteria) this;
        }

        public Criteria andSmsmobilenoIn(List<String> values) {
            addCriterion("SMSMOBILENO in", values, "smsmobileno");
            return (Criteria) this;
        }

        public Criteria andSmsmobilenoNotIn(List<String> values) {
            addCriterion("SMSMOBILENO not in", values, "smsmobileno");
            return (Criteria) this;
        }

        public Criteria andSmsmobilenoBetween(String value1, String value2) {
            addCriterion("SMSMOBILENO between", value1, value2, "smsmobileno");
            return (Criteria) this;
        }

        public Criteria andSmsmobilenoNotBetween(String value1, String value2) {
            addCriterion("SMSMOBILENO not between", value1, value2, "smsmobileno");
            return (Criteria) this;
        }

        public Criteria andOverfeetypeIsNull() {
            addCriterion("OVERFEETYPE is null");
            return (Criteria) this;
        }

        public Criteria andOverfeetypeIsNotNull() {
            addCriterion("OVERFEETYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOverfeetypeEqualTo(Integer value) {
            addCriterion("OVERFEETYPE =", value, "overfeetype");
            return (Criteria) this;
        }

        public Criteria andOverfeetypeNotEqualTo(Integer value) {
            addCriterion("OVERFEETYPE <>", value, "overfeetype");
            return (Criteria) this;
        }

        public Criteria andOverfeetypeGreaterThan(Integer value) {
            addCriterion("OVERFEETYPE >", value, "overfeetype");
            return (Criteria) this;
        }

        public Criteria andOverfeetypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("OVERFEETYPE >=", value, "overfeetype");
            return (Criteria) this;
        }

        public Criteria andOverfeetypeLessThan(Integer value) {
            addCriterion("OVERFEETYPE <", value, "overfeetype");
            return (Criteria) this;
        }

        public Criteria andOverfeetypeLessThanOrEqualTo(Integer value) {
            addCriterion("OVERFEETYPE <=", value, "overfeetype");
            return (Criteria) this;
        }

        public Criteria andOverfeetypeIn(List<Integer> values) {
            addCriterion("OVERFEETYPE in", values, "overfeetype");
            return (Criteria) this;
        }

        public Criteria andOverfeetypeNotIn(List<Integer> values) {
            addCriterion("OVERFEETYPE not in", values, "overfeetype");
            return (Criteria) this;
        }

        public Criteria andOverfeetypeBetween(Integer value1, Integer value2) {
            addCriterion("OVERFEETYPE between", value1, value2, "overfeetype");
            return (Criteria) this;
        }

        public Criteria andOverfeetypeNotBetween(Integer value1, Integer value2) {
            addCriterion("OVERFEETYPE not between", value1, value2, "overfeetype");
            return (Criteria) this;
        }

        public Criteria andPayfeeIsNull() {
            addCriterion("PAYFEE is null");
            return (Criteria) this;
        }

        public Criteria andPayfeeIsNotNull() {
            addCriterion("PAYFEE is not null");
            return (Criteria) this;
        }

        public Criteria andPayfeeEqualTo(Integer value) {
            addCriterion("PAYFEE =", value, "payfee");
            return (Criteria) this;
        }

        public Criteria andPayfeeNotEqualTo(Integer value) {
            addCriterion("PAYFEE <>", value, "payfee");
            return (Criteria) this;
        }

        public Criteria andPayfeeGreaterThan(Integer value) {
            addCriterion("PAYFEE >", value, "payfee");
            return (Criteria) this;
        }

        public Criteria andPayfeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PAYFEE >=", value, "payfee");
            return (Criteria) this;
        }

        public Criteria andPayfeeLessThan(Integer value) {
            addCriterion("PAYFEE <", value, "payfee");
            return (Criteria) this;
        }

        public Criteria andPayfeeLessThanOrEqualTo(Integer value) {
            addCriterion("PAYFEE <=", value, "payfee");
            return (Criteria) this;
        }

        public Criteria andPayfeeIn(List<Integer> values) {
            addCriterion("PAYFEE in", values, "payfee");
            return (Criteria) this;
        }

        public Criteria andPayfeeNotIn(List<Integer> values) {
            addCriterion("PAYFEE not in", values, "payfee");
            return (Criteria) this;
        }

        public Criteria andPayfeeBetween(Integer value1, Integer value2) {
            addCriterion("PAYFEE between", value1, value2, "payfee");
            return (Criteria) this;
        }

        public Criteria andPayfeeNotBetween(Integer value1, Integer value2) {
            addCriterion("PAYFEE not between", value1, value2, "payfee");
            return (Criteria) this;
        }

        public Criteria andBranchIsNull() {
            addCriterion("BRANCH is null");
            return (Criteria) this;
        }

        public Criteria andBranchIsNotNull() {
            addCriterion("BRANCH is not null");
            return (Criteria) this;
        }

        public Criteria andBranchEqualTo(String value) {
            addCriterion("BRANCH =", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotEqualTo(String value) {
            addCriterion("BRANCH <>", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchGreaterThan(String value) {
            addCriterion("BRANCH >", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchGreaterThanOrEqualTo(String value) {
            addCriterion("BRANCH >=", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchLessThan(String value) {
            addCriterion("BRANCH <", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchLessThanOrEqualTo(String value) {
            addCriterion("BRANCH <=", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchLike(String value) {
            addCriterion("BRANCH like", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotLike(String value) {
            addCriterion("BRANCH not like", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchIn(List<String> values) {
            addCriterion("BRANCH in", values, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotIn(List<String> values) {
            addCriterion("BRANCH not in", values, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchBetween(String value1, String value2) {
            addCriterion("BRANCH between", value1, value2, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotBetween(String value1, String value2) {
            addCriterion("BRANCH not between", value1, value2, "branch");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andBossidIsNull() {
            addCriterion("BOSSID is null");
            return (Criteria) this;
        }

        public Criteria andBossidIsNotNull() {
            addCriterion("BOSSID is not null");
            return (Criteria) this;
        }

        public Criteria andBossidEqualTo(String value) {
            addCriterion("BOSSID =", value, "bossid");
            return (Criteria) this;
        }

        public Criteria andBossidNotEqualTo(String value) {
            addCriterion("BOSSID <>", value, "bossid");
            return (Criteria) this;
        }

        public Criteria andBossidGreaterThan(String value) {
            addCriterion("BOSSID >", value, "bossid");
            return (Criteria) this;
        }

        public Criteria andBossidGreaterThanOrEqualTo(String value) {
            addCriterion("BOSSID >=", value, "bossid");
            return (Criteria) this;
        }

        public Criteria andBossidLessThan(String value) {
            addCriterion("BOSSID <", value, "bossid");
            return (Criteria) this;
        }

        public Criteria andBossidLessThanOrEqualTo(String value) {
            addCriterion("BOSSID <=", value, "bossid");
            return (Criteria) this;
        }

        public Criteria andBossidLike(String value) {
            addCriterion("BOSSID like", value, "bossid");
            return (Criteria) this;
        }

        public Criteria andBossidNotLike(String value) {
            addCriterion("BOSSID not like", value, "bossid");
            return (Criteria) this;
        }

        public Criteria andBossidIn(List<String> values) {
            addCriterion("BOSSID in", values, "bossid");
            return (Criteria) this;
        }

        public Criteria andBossidNotIn(List<String> values) {
            addCriterion("BOSSID not in", values, "bossid");
            return (Criteria) this;
        }

        public Criteria andBossidBetween(String value1, String value2) {
            addCriterion("BOSSID between", value1, value2, "bossid");
            return (Criteria) this;
        }

        public Criteria andBossidNotBetween(String value1, String value2) {
            addCriterion("BOSSID not between", value1, value2, "bossid");
            return (Criteria) this;
        }

        public Criteria andApplyoidIsNull() {
            addCriterion("APPLYOID is null");
            return (Criteria) this;
        }

        public Criteria andApplyoidIsNotNull() {
            addCriterion("APPLYOID is not null");
            return (Criteria) this;
        }

        public Criteria andApplyoidEqualTo(String value) {
            addCriterion("APPLYOID =", value, "applyoid");
            return (Criteria) this;
        }

        public Criteria andApplyoidNotEqualTo(String value) {
            addCriterion("APPLYOID <>", value, "applyoid");
            return (Criteria) this;
        }

        public Criteria andApplyoidGreaterThan(String value) {
            addCriterion("APPLYOID >", value, "applyoid");
            return (Criteria) this;
        }

        public Criteria andApplyoidGreaterThanOrEqualTo(String value) {
            addCriterion("APPLYOID >=", value, "applyoid");
            return (Criteria) this;
        }

        public Criteria andApplyoidLessThan(String value) {
            addCriterion("APPLYOID <", value, "applyoid");
            return (Criteria) this;
        }

        public Criteria andApplyoidLessThanOrEqualTo(String value) {
            addCriterion("APPLYOID <=", value, "applyoid");
            return (Criteria) this;
        }

        public Criteria andApplyoidLike(String value) {
            addCriterion("APPLYOID like", value, "applyoid");
            return (Criteria) this;
        }

        public Criteria andApplyoidNotLike(String value) {
            addCriterion("APPLYOID not like", value, "applyoid");
            return (Criteria) this;
        }

        public Criteria andApplyoidIn(List<String> values) {
            addCriterion("APPLYOID in", values, "applyoid");
            return (Criteria) this;
        }

        public Criteria andApplyoidNotIn(List<String> values) {
            addCriterion("APPLYOID not in", values, "applyoid");
            return (Criteria) this;
        }

        public Criteria andApplyoidBetween(String value1, String value2) {
            addCriterion("APPLYOID between", value1, value2, "applyoid");
            return (Criteria) this;
        }

        public Criteria andApplyoidNotBetween(String value1, String value2) {
            addCriterion("APPLYOID not between", value1, value2, "applyoid");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIsNull() {
            addCriterion("ORDERTIME is null");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIsNotNull() {
            addCriterion("ORDERTIME is not null");
            return (Criteria) this;
        }

        public Criteria andOrdertimeEqualTo(Date value) {
            addCriterion("ORDERTIME =", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotEqualTo(Date value) {
            addCriterion("ORDERTIME <>", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeGreaterThan(Date value) {
            addCriterion("ORDERTIME >", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ORDERTIME >=", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeLessThan(Date value) {
            addCriterion("ORDERTIME <", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeLessThanOrEqualTo(Date value) {
            addCriterion("ORDERTIME <=", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIn(List<Date> values) {
            addCriterion("ORDERTIME in", values, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotIn(List<Date> values) {
            addCriterion("ORDERTIME not in", values, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeBetween(Date value1, Date value2) {
            addCriterion("ORDERTIME between", value1, value2, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotBetween(Date value1, Date value2) {
            addCriterion("ORDERTIME not between", value1, value2, "ordertime");
            return (Criteria) this;
        }

        public Criteria andPaytimeIsNull() {
            addCriterion("PAYTIME is null");
            return (Criteria) this;
        }

        public Criteria andPaytimeIsNotNull() {
            addCriterion("PAYTIME is not null");
            return (Criteria) this;
        }

        public Criteria andPaytimeEqualTo(Date value) {
            addCriterion("PAYTIME =", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeNotEqualTo(Date value) {
            addCriterion("PAYTIME <>", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeGreaterThan(Date value) {
            addCriterion("PAYTIME >", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PAYTIME >=", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeLessThan(Date value) {
            addCriterion("PAYTIME <", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeLessThanOrEqualTo(Date value) {
            addCriterion("PAYTIME <=", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeIn(List<Date> values) {
            addCriterion("PAYTIME in", values, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeNotIn(List<Date> values) {
            addCriterion("PAYTIME not in", values, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeBetween(Date value1, Date value2) {
            addCriterion("PAYTIME between", value1, value2, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeNotBetween(Date value1, Date value2) {
            addCriterion("PAYTIME not between", value1, value2, "paytime");
            return (Criteria) this;
        }

        public Criteria andTranstimeIsNull() {
            addCriterion("TRANSTIME is null");
            return (Criteria) this;
        }

        public Criteria andTranstimeIsNotNull() {
            addCriterion("TRANSTIME is not null");
            return (Criteria) this;
        }

        public Criteria andTranstimeEqualTo(Date value) {
            addCriterion("TRANSTIME =", value, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeNotEqualTo(Date value) {
            addCriterion("TRANSTIME <>", value, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeGreaterThan(Date value) {
            addCriterion("TRANSTIME >", value, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeGreaterThanOrEqualTo(Date value) {
            addCriterion("TRANSTIME >=", value, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeLessThan(Date value) {
            addCriterion("TRANSTIME <", value, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeLessThanOrEqualTo(Date value) {
            addCriterion("TRANSTIME <=", value, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeIn(List<Date> values) {
            addCriterion("TRANSTIME in", values, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeNotIn(List<Date> values) {
            addCriterion("TRANSTIME not in", values, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeBetween(Date value1, Date value2) {
            addCriterion("TRANSTIME between", value1, value2, "transtime");
            return (Criteria) this;
        }

        public Criteria andTranstimeNotBetween(Date value1, Date value2) {
            addCriterion("TRANSTIME not between", value1, value2, "transtime");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNull() {
            addCriterion("PAYTYPE is null");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNotNull() {
            addCriterion("PAYTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPaytypeEqualTo(String value) {
            addCriterion("PAYTYPE =", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotEqualTo(String value) {
            addCriterion("PAYTYPE <>", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThan(String value) {
            addCriterion("PAYTYPE >", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThanOrEqualTo(String value) {
            addCriterion("PAYTYPE >=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThan(String value) {
            addCriterion("PAYTYPE <", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThanOrEqualTo(String value) {
            addCriterion("PAYTYPE <=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLike(String value) {
            addCriterion("PAYTYPE like", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotLike(String value) {
            addCriterion("PAYTYPE not like", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeIn(List<String> values) {
            addCriterion("PAYTYPE in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotIn(List<String> values) {
            addCriterion("PAYTYPE not in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeBetween(String value1, String value2) {
            addCriterion("PAYTYPE between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotBetween(String value1, String value2) {
            addCriterion("PAYTYPE not between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andAgentCodeIsNull() {
            addCriterion("AGENT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andAgentCodeIsNotNull() {
            addCriterion("AGENT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andAgentCodeEqualTo(String value) {
            addCriterion("AGENT_CODE =", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeNotEqualTo(String value) {
            addCriterion("AGENT_CODE <>", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeGreaterThan(String value) {
            addCriterion("AGENT_CODE >", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeGreaterThanOrEqualTo(String value) {
            addCriterion("AGENT_CODE >=", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeLessThan(String value) {
            addCriterion("AGENT_CODE <", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeLessThanOrEqualTo(String value) {
            addCriterion("AGENT_CODE <=", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeLike(String value) {
            addCriterion("AGENT_CODE like", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeNotLike(String value) {
            addCriterion("AGENT_CODE not like", value, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeIn(List<String> values) {
            addCriterion("AGENT_CODE in", values, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeNotIn(List<String> values) {
            addCriterion("AGENT_CODE not in", values, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeBetween(String value1, String value2) {
            addCriterion("AGENT_CODE between", value1, value2, "agentCode");
            return (Criteria) this;
        }

        public Criteria andAgentCodeNotBetween(String value1, String value2) {
            addCriterion("AGENT_CODE not between", value1, value2, "agentCode");
            return (Criteria) this;
        }

        public Criteria andSubChannelIsNull() {
            addCriterion("SUB_CHANNEL is null");
            return (Criteria) this;
        }

        public Criteria andSubChannelIsNotNull() {
            addCriterion("SUB_CHANNEL is not null");
            return (Criteria) this;
        }

        public Criteria andSubChannelEqualTo(String value) {
            addCriterion("SUB_CHANNEL =", value, "subChannel");
            return (Criteria) this;
        }

        public Criteria andSubChannelNotEqualTo(String value) {
            addCriterion("SUB_CHANNEL <>", value, "subChannel");
            return (Criteria) this;
        }

        public Criteria andSubChannelGreaterThan(String value) {
            addCriterion("SUB_CHANNEL >", value, "subChannel");
            return (Criteria) this;
        }

        public Criteria andSubChannelGreaterThanOrEqualTo(String value) {
            addCriterion("SUB_CHANNEL >=", value, "subChannel");
            return (Criteria) this;
        }

        public Criteria andSubChannelLessThan(String value) {
            addCriterion("SUB_CHANNEL <", value, "subChannel");
            return (Criteria) this;
        }

        public Criteria andSubChannelLessThanOrEqualTo(String value) {
            addCriterion("SUB_CHANNEL <=", value, "subChannel");
            return (Criteria) this;
        }

        public Criteria andSubChannelLike(String value) {
            addCriterion("SUB_CHANNEL like", value, "subChannel");
            return (Criteria) this;
        }

        public Criteria andSubChannelNotLike(String value) {
            addCriterion("SUB_CHANNEL not like", value, "subChannel");
            return (Criteria) this;
        }

        public Criteria andSubChannelIn(List<String> values) {
            addCriterion("SUB_CHANNEL in", values, "subChannel");
            return (Criteria) this;
        }

        public Criteria andSubChannelNotIn(List<String> values) {
            addCriterion("SUB_CHANNEL not in", values, "subChannel");
            return (Criteria) this;
        }

        public Criteria andSubChannelBetween(String value1, String value2) {
            addCriterion("SUB_CHANNEL between", value1, value2, "subChannel");
            return (Criteria) this;
        }

        public Criteria andSubChannelNotBetween(String value1, String value2) {
            addCriterion("SUB_CHANNEL not between", value1, value2, "subChannel");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("CHANNEL is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("CHANNEL is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(String value) {
            addCriterion("CHANNEL =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(String value) {
            addCriterion("CHANNEL <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(String value) {
            addCriterion("CHANNEL >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(String value) {
            addCriterion("CHANNEL <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLike(String value) {
            addCriterion("CHANNEL like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotLike(String value) {
            addCriterion("CHANNEL not like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<String> values) {
            addCriterion("CHANNEL in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<String> values) {
            addCriterion("CHANNEL not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(String value1, String value2) {
            addCriterion("CHANNEL between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(String value1, String value2) {
            addCriterion("CHANNEL not between", value1, value2, "channel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated do_not_delete_during_merge Sat May 08 16:03:28 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TF_PAYBADDEBT_ORDERS
     *
     * @mbg.generated Sat May 08 16:03:28 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}