package com.sunwj.mybatis.mapper;

import com.sunwj.mybatis.bean.DepartmentExample;
import com.sunwj.mybatis.bean.DepartmentExampleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentExampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    long countByExample(DepartmentExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int deleteByExample(DepartmentExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int insert(DepartmentExample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int insertSelective(DepartmentExample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    List<DepartmentExample> selectByExample(DepartmentExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    DepartmentExample selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") DepartmentExample record, @Param("example") DepartmentExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int updateByExample(@Param("record") DepartmentExample record, @Param("example") DepartmentExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int updateByPrimaryKeySelective(DepartmentExample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int updateByPrimaryKey(DepartmentExample record);
}