package com.sunwj.mybatis.mapper;

import com.sunwj.mybatis.bean.EmployeeExample;
import com.sunwj.mybatis.bean.EmployeeExampleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeExampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    long countByExample(EmployeeExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int deleteByExample(EmployeeExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int insert(EmployeeExample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int insertSelective(EmployeeExample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    List<EmployeeExample> selectByExample(EmployeeExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    EmployeeExample selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") EmployeeExample record, @Param("example") EmployeeExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int updateByExample(@Param("record") EmployeeExample record, @Param("example") EmployeeExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int updateByPrimaryKeySelective(EmployeeExample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed May 05 21:26:38 CST 2021
     */
    int updateByPrimaryKey(EmployeeExample record);
}